dist: trusty
language: node_js
node_js:
  - "6.10.0"
python:
  - "3.6"

sudo: required

services:
  - docker

cache:
  directories:
    - ui/node_modules
    - components/core

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
script: 
  - ./setup.sh 
  - cd ui && npm install && npm test
  - cd components/core && python setup.py develop && python Main.py

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t scorelab/Bassa components/core;
    docker push scorelab/Bassa;
    fi
