version: "3"
services:
  web:
    build: .
      ports:
        - "3000:3000"
      labels:
        com.example.description: "Docker container for Bassa UI"
  api:
    build: .
      ports:
        - "8000:8000"
      depends_on:
        - "db"
      labels:
        com.example.description: "Docker container for Bassa backend"
  db:
    image: mysql
    restart: always
    volumes:
      - data-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${BASSA_DB_NAME}
      MYSQL_USER: ${BASSA_DB_USERNAME}
      MYSQL_PASSWORD: ${BASSA_DB_PASSWORD} 
